[package]
name = "nasaapodviewer-frontend"
<<<<<<< HEAD
version = "136.0.3"
=======
version = "138.0.2"
>>>>>>> 11bbb750dab4c7b1e17c677f495af3fcf4041528
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
gloo-net = { version = "0.5.0", features = [ "json" ]}
serde = { version = "1.0.196", features = ["derive"] }
url = "2.5.0"
wasm-bindgen-futures = "0.4.41"
yew = { version = "0.21.0", features = ["csr"] }
