[package]
name = "nasaapodviewer-server"
version = "141.0.0"
edition = "2021"
authors = [ "Jeffery D. Mitchell", "<crusty-rustacean@jeffmitchelldev.com>" ]
publish = false

[dependencies]
rocket = "0.5.0"
shuttle-rocket = "0.41.0"
shuttle-runtime = "0.41.0"
tokio = "1.36.0"
