[package]
name = "nasa-imagery-viewer-server"
version = "1.46.1"
edition = "2021"
authors = [ "Jeffery D. Mitchell", "<sentinl1909@jeff-mitchell.dev>" ]
publish = false

[dependencies]
rocket = "0.5.0"
shuttle-rocket = "0.46.0"
shuttle-runtime = "0.46.0"
tokio = "1"
